api:
  key: 57A18EB11E094880BECDFCED9DE00BA5
plugins:
  announcements:
    _config_version: 1
  discovery:
    upnpUuid: ed0699e3-ed91-4023-b58a-c61bd934861e
  errortracking:
    unique_id: 23d6dcc6-5477-4dbc-9898-33b9c372c905
  softwareupdate:
    _config_version: 6
    check_providers:
      active_filters: active_filters
      cost: cost
      customcontrol: customControl
      portlister: portlister
      requestspinner: requestspinner
      systemcommandeditor: systemcommandeditor
      touchui: touchui
      yamlpatcher: yamlpatcher
  tracking:
    unique_id: 87955ef9-94e3-4ad1-9c44-747b55aaff56
printerProfiles:
  default: _default
server:
  secretKey: 60J8szSq4Mu6i5boKYeWHbVyTiSb6FXb
